trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    echo "Instalando dependencias básicas..."
    sudo apt-get update
    sudo apt-get install -y php
    php -v
  displayName: 'Instalar PHP'

- script: |
    echo "Validando archivos HTML..."
    find . -name "*.html" -exec echo "Archivo encontrado: {}" \;
  displayName: 'Validar HTML'

- script: |
    echo "Simulando despliegue..."
    echo "¡Pipeline ejecutado con éxito!"
  displayName: 'Paso final'
